{{- if .Values.applicationSecret.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vas.applicationSecret.name" . }}
type: Opaque
stringData:
  keycloak-secret: {{ .Values.applicationSecret.keycloak }}
  cdq-key: {{ .Values.applicationSecret.cdq }}

{{- end }}