version: '2'
services:
  database:
    image: postgres:latest # use latest official postgres version
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: default
        POSTGRES_PASSWORD: defaultpassword
        POSTGRES_DB: database
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
