{{- if .Values.applicationSecret.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vas.applicationSecret.name" . }}
type: Opaque
stringData:
  keycloak-secret: {{ .Values.applicationSecret.client-secret }}
  client-id: {{ .Values.applicationSecret.client-id }}

{{- end }}