# Spring Boot configuration
spring:
  config:
    activate:
      on-profile: int
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${vas.authentication-url.token-url}
      resourceserver:
        jwt:
          jwk-set-uri: ${vas.authentication-url.jwk-set-uri}

application:
  name: int
