

# Spring Boot configuration
spring:
  config:
    activate:
      on-profile: local

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/vas;DB_CLOSE_DELAY=-1
    username: vas
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    properties:
      hibernate:
        show_sql: false
        format_sql: true
cors:
  origins: >
    http://localhost:4200/,
    https://traceability-portal.dev.demo.catena-x.net/,
    https://traceability-portal.int.demo.catena-x.net/

application:
  host: http://localhost:8080/api/dashboard