

# Spring Boot configuration
spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: user
    url: jdbc:postgresql://localhost:5432/database
    driverClassName: org.postgresql.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:h2:file:./target/h2db/db/vas;DB_CLOSE_DELAY=-1
#    username: vas
#    password:
#    hikari:
#      poolName: Hikari
#      auto-commit: false
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    database: H2
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: true

security:
  enabled: false


application:
  host: http://localhost:8080/api/dashboard
  partnersPoolUrl:
    legalEntities: 'https://partners-pool.dev.demo.catena-x.net/api/catena/legal-entities'