server:
  port: 8080
  tomcat:
    relaxedPathChars: "|,{,},[,]"
    relaxedQueryChars: "|,{,},[,]"



vas:
  datasource:
    host: localhost
    user: default
    pass: defaultpassword

spring:
  application:
    name: value-added-service
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: Cl16-CX-CRisk
            client-secret: gtdSaoG51RpjXDyfthpiGjhH3JQWmzIU
        provider:
          keycloak:
            token-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

keycloak:
  enabled: true
  realm: CX-Central #jhipster #CX-Central
  auth-server-url: https://centralidp.dev.demo.catena-x.net/auth #http://localhost:9080/auth #https://centralidp.dev.demo.catena-x.net/auth
  #token-url: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/auth
  #auth-url: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
  resource: Cl16-CX-CRisk #spring-boot
  public-client: true
  bearer-only: true
  credentials:
    secret: gtdSaoG51RpjXDyfthpiGjhH3JQWmzIU
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  ssl-required: NONE
  securityconstraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
            - /api/*



#  bearer-only: true
#  credentials.secret: gtdSaoG51RpjXDyfthpiGjhH3JQWmzIU
#  public-client: false
#  use-resource-role-mappings: true
#  principal-attribute: preferred_username
#  ssl-required: external


logging:
  level:
    root: INFO
    com.catenax.valueaddedservice: DEBUG

application:
  name: default
  host: project-value-added-service-vas/api/dashboard

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers', 'prometheus', 'threaddump', 'caches']
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

