server:
  port: 8080

vas:
  datasource:
    host: localhost
    user: vas
    password: ''

spring:
  application:
    name: value-added-service

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers', 'prometheus', 'threaddump', 'caches']
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

