# Spring Boot configuration
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: vas
    url: jdbc:postgresql://${vas.datasource.host}:5432/vas
    driverClassName: org.postgresql.Driver
    password: ${vas_datasource_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

application:
  name: dev
  host: http://project-value-added-service-vas/api/schedule