apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.yaml: |-
    hazelcast:
      network:
        port:
          auto-increment: true
          port-count: 100
          port: 5701
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            namespace: template
            service-name: hazelcast-service
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
