apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  annotations:
    avp.kubernetes.io/path: "dft/data/postgres"
    avp.kubernetes.io/secret-version: "9"
type: Opaque
stringData:
  dbName: <DB_NAME>
  dbUser: <DB_USERNAME>
  dbPassword: <DB_PASSWORD>
